model:
  default: nvidia/nemotron-3-super-120b-a12b
  provider: nvidia
_config_version: 49
platform_toolsets:
  cli:
  - clarify
  - computer_use
  - connections
  - cronjob
  - delegation
  - file
  - image_gen
  - kanban
  - memory
  - session_search
  - skills
  - todo
  - tts
  - vision
known_plugin_toolsets:
  cli:
  - a2a
  - spotify
known_builtin_toolsets:
  cli:
  - browser
  - clarify
  - code_execution
  - computer_use
  - connections
  - context_engine
  - cronjob
  - delegation
  - discord
  - discord_admin
  - file
  - homeassistant
  - image_gen
  - kanban
  - memory
  - session_search
  - skills
  - spotify
  - stt
  - terminal
  - todo
  - tts
  - video
  - video_gen
  - vision
  - web
  - x_search
  - yuanbao

fallback_providers:
- provider: gemini
  model: gemini-3.8-flash
- provider: zai
  model: glm-5.3
- provider: openrouter
  model: nvidia/nemotron-3-super-120b-a12b:free
